### ISSUE TITLE
Wrong dependency; should be using BepInEx-BepInExPack

### ISSUE THREAD

**Issue by solidterre** [PortableNavi/better_inverse_teleporter#1]
You should be using the [BepInEx-BepInExPack](https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/) dependency but are using a deprecated one: bbepis-BepInExPack-5.4.2113

Could you resolve this and push a new 2.0.0 version please ? This is causing issues with other mods.

At this time your mod is unusable for some people :-)

**Comment by rboeni2s** [comment]
Sure, I'll have a look at it tomorrow

**Comment by rboeni2s** [comment]
It should be fixed now
